metadata:
  model_type: QW-MTL (Deep Learning)
  mean_performance: 0.8432766547805173
  features_used:
    DMPNN: true
    Morgan: false
    RDKit: true
    Quantum: true
  parameters:
    lr: 0.0005
    batch_size: 64
    epochs_trained: 10
tasks:
  ames:
    score: 0.8607910742649053
    metric: ROC-AUC
  bbb_martins:
    score: 0.9230119634060521
    metric: ROC-AUC
  bioavailability_ma:
    score: 0.6953242835595776
    metric: ROC-AUC
  cyp2c9_substrate_carbonmangels:
    score: 0.6134453781512605
    metric: ROC-AUC
  cyp2c9_veith:
    score: 0.8961301665713556
    metric: ROC-AUC
  cyp2d6_substrate_carbonmangels:
    score: 0.807070707070707
    metric: ROC-AUC
  cyp2d6_veith:
    score: 0.8645627876397107
    metric: ROC-AUC
  cyp3a4_substrate_carbonmangels:
    score: 0.7173489278752436
    metric: ROC-AUC
  cyp3a4_veith:
    score: 0.8862157136215714
    metric: ROC-AUC
  dili:
    score: 0.9241622574955908
    metric: ROC-AUC
  hERG_Karim:
    score: 0.8803024832599792
    metric: ROC-AUC
  hia_hou:
    score: 0.9615384615384616
    metric: ROC-AUC
  pgp_broccatelli:
    score: 0.9326923076923077
    metric: ROC-AUC
